<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.iis2024</groupId>
  <artifactId>date</artifactId>
  <version>1.0-SNAPSHOT</version>
  <packaging>jar</packaging>

  <name>date</name>
  <url>http://maven.apache.org</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>19</maven.compiler.source>
    <maven.compiler.target>19</maven.compiler.target>
  </properties>

  <Vale 😏, punto número dos 📍, lo vais a ver 👀 mucho mejor 💅 que en el canal 📺 de IlloJuan 🤓, que en el canal 💻 de AlexelCapo 🎮, que en el canal 📡 de tal 🙄, mucho mejor 😌. Porque yo streameo 📡 X264 🧠 con, eh 😬, doble keyframe 🔁 de intervalo ⏱️, streameo 🧑‍💻 tirando de microprocesador ⚙️, streameo otra vez 😤 en 8.000 de bit rate 📈 constante 💪, pero codificado 🔒 con el microprocesador 🧩, por tanto 🤔, la tasa de información 🧾 por píxel 🧮 es mucho mayor 📊 y no vais 💬 a poder compararlo 🤷‍♂️ con el nivel 🧠 de calidad 💎 de los demás streamers 🎭.
Esto lo quiero 🗣️ dejar dicho 📢 para los especialistas 🧐 que eeee 😅 que queráis tener 🧠 un poquito 🧃 más de conocimiento 📚 y de cultura 🎓 general, que nunca 🚫 viene mal 😌, ¿vale? 👍
O sea 😏 que tened en cuenta 💭 que vosotros lo vais 🧍‍♂️ a ver 👁️ mucho mejor 🌟 en mi directo 🔴 que en el de los demás 😤.
Ahora ⏰, esperemos 🙏 que la capturadora 🎥 no me falle 💀.>

  <dependencias>
    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <version>5.10.2</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
</projecto>
